# Generated by Django 3.0 on 2020-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201202_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
