# Generated by Django 3.0 on 2020-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_assignment_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='adte_created',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='student',
            name='assignments',
            field=models.ManyToManyField(to='main.Assignment'),
        ),
    ]
