# Generated by Django 3.0 on 2020-12-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201203_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='files_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
